---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapiforhikka-webapi
  labels:
    app: webapiforhikka-webapi
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webapiforhikka-webapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapiforhikka-webapi
    spec:
      containers:
      - name: webapiforhikka-webapi
        image: webapiforhikka-webapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: webapiforhikka-webapi-env
      terminationGracePeriodSeconds: 180