services:
  web-api:
    container_name: web-api-for-hikka
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - dotnetcorepromgrafana
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - dotnetcorepromgrafana

  grafana: 
    image: grafana/grafana
    #command:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    restart: always
    ports:
      - "3000:3000"
    networks:
      - dotnetcorepromgrafana
        
  db:
    container_name: db-for-hikka
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hikka
    ports:
        - "5432:5432"
    networks:
      - dotnetcorepromgrafana
      
### put all the networks here
networks:
  dotnetcorepromgrafana: